# -*- coding: utf-8 -*-
"""создание базы данных и простые запросы 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Y4ZPp_I5nW78BX-zh3QMbrcagxkla2S
"""

import sqlite3

my_database = sqlite3.connect('database.db')
cur = my_database.cursor()
my_database.commit()

cur.execute("""CREATE TABLE IF NOT EXISTS abiturients(
        id INT PRIMARY KEY,
        scores INT);
      """)
my_database.commit()

cur.execute("""INSERT INTO abiturients(id, scores)
VALUES
       ('3', '46'),
       ('4', '91'),
       ('5', '25'),
       ('6', '78'),
       ('7', '56'),
       ('8', '37'),
       ('9', '81'),
       ('10', '62'),
       ('11', '21'),
       ('12', '79'),
       ('13', '96'),
       ('14', '36'),
       ('15', '19'),
       ('16', '49'),
       ('17', '53');""")
my_database.commit()

cur.execute("SELECT * FROM abiturients;")
print(cur.fetchall())

cur.execute("""ALTER TABLE abiturients RENAME TO EXAMINATION;""")

"""Сортировка абитуриентов по количеству набранных баллов на экзамене. Рейтинг:"""

cur.execute("""SELECT * FROM EXAMINATION ORDER BY scores DESC;""")
print(cur.fetchall())

"""Ответ на вопрос второго задания. Диапазон возможного количества строк в результирующей таблице минимально 30 строк и максимально 600."""